language: python

python:
  - "2.7"
  - "pypy"

install:
  - pip install -U pytest

script:
  - wget http://cs.unm.edu/~stelleg/coq-8.6-5-x86_64.pkg.tar.xz
  - tar xf coq-8.6-5-x86_64.pkg.tar.xz
  - export PATH=$PWD/usr/bin:$PATH
  - pytest -q ./autoload/test.py
